version: '3'
services:
  frontend:
    image: fogelsharp/lalafront:latest
    build: .

    ports:
      - 80:80
    links:
      - backend
  backend:
    image: fogelsharp/lalaback:latest
    build: .
    ports:
      - 30555:30555
    environment:
      - MONGO_URL=mongo
    links:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9000:9443
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

